image: "python:latest"

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
      pytest pytest-xdist nbval pytest-cov pytest-rerunfailures

# Set up caching as suggested by GitLab's Python template
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths: [.cache/pip,venv]

stages:
  - test
  - deploy

# Execute all available code. Most of our "tests" are actually the
# notebooks, so we use the nbval extension to pull them into py.test.
# This has the advantage that we can generate coverage statistics for
# the entire thing.
#
# Unfortunately, there currently seems to be some flakiness to this:
# Sometimes a notebook fails to start, reporting "RuntimeError: Kernel
# didn't respond in 60 seconds". There's open tickets on similar
# issues, so maybe this is going to away eventually. For the moment,
# simply retrying a couple of times seems to fix it. This likely means
# that we spin a bit if something goes wrong systematically, but
# better than dealing with random false positives...
test:
  stage: test
  tags: [k8srunner]
  script:
    - py.test --verbose --color=yes --junitxml=junit.xml
        --cov=sdp_par_model --cov-report=term --cov-report=html
        -n 4 --dist loadscope --nbval-lax
        notebooks/SKA1_Export.ipynb
        notebooks/SKA1_SDP_Products.ipynb
        notebooks/SKA1_Imaging_Performance_Model.ipynb
        notebooks/SKA1_Scheduling_New.ipynb
        tests
  artifacts:
    paths: [htmlcov/, junit.xml]
    reports:
      junit: junit.xml

# Generate GitLab pages. This is done only for the master. On this
# occasion, we export:
#
# 1. The Sphinx documentation (root)
# 2. All the notebooks (note that this will re-run them)
# 3. Coverage reports
pages:
  stage: deploy
  tags: [k8srunner]
  only: [master]
  dependencies: [test] # For coverage
  script:
    # Make Sphinx documentation
    - pip install sphinx sphinx-rtd-theme
    - make -C docs html
    # Make notebooks
    - make -j 4 -k -C notebooks notebooks_html
    # Copy all into "public"
    - cp -R docs/_build/html public
    - cp -R notebooks/out public/notebooks
    - cp -R htmlcov public
  artifacts:
    paths: [public/]
    expire_in: 1 week
